### ISSUE TITLE
Inference performance with HumanML-trained model is significantly lower then Babel-trained model

### ISSUE THREAD

**Issue by senecobis** [BarqueroGerman/FlowMDM#14]
Hi, I was testing the two different models with custom labels.
I have consistently noticed that HumanML trained model perform significantly worser then babel-trained model.
This could make sense, as the HumanML dataset doesn’t feature continuously varying labeled motions like Babel.
But the problem often resides in the single motion itself (not really in the transition). 

I tested putting higher guidance parameters for HumanML, but still the motion isn't performed at all or is somewhat wrong(see squat in the example).
These results also seems to not match the papers results, where for instance in Table 4. the performances of HumanML trained seems to be better then Babel-trained.

You can see here two videos, the first produced with babel, the second with Human ML. The parameters used match the ones reported in README and Paper. The test was done with three actions as follows {walk -> 300, jump -> 300, squat -> 300}.

Babel -> https://github.com/user-attachments/assets/711a23b5-9bec-437e-b2df-ca4e0018fa8d

HumanML -> https://github.com/user-attachments/assets/3d94ea9b-221f-43d4-a4d0-99684116ca1b

**Comment by BarqueroGerman** [comment]
Hi Roberto,

Thanks for your interest in our work! Some degradation is expected when using custom labels + lengths, which in this particular case are quite different from those seen at training time. If you inspect the textual descriptions of HumanML3D you will observe that they are usually longer and more descriptive than those you provide. So Babel works better in your samples due to 1) explicit supervised learning for learning transitions, 2) the labels you use are similar to Babel’s training labels.
