### ISSUE TITLE
Confusion about the canonicalization.

### ISSUE THREAD

**Issue by hoyeYang** [BarqueroGerman/FlowMDM#15]
Great work! But I'm confused about these lines https://github.com/BarqueroGerman/FlowMDM/blob/e81c67fa02c5284b4b32a757c575c9b9fcaaa82a/data_loaders/amass/transforms/rots2rfeats/globvelandy.py#L69-L73

Assuming the original rot2d is $(x\theta, y\theta, z\theta)$, directly transforming the rot2d represented by axis-angle into $(0, 0, z\theta+\frac{\pi}{2})$ seems confusing.

If the canonicalization is removed, will the experimental results be significantly affected?

**Comment by BarqueroGerman** [comment]
Hi!

Thanks for your interest in our work! The canonicalization and most of the data processing step is inherited from [TEACH](https://github.com/atnikos/teach/tree/54a2a1ae09ad4f61da81d79e505e2da3da87bd82). Since this transformation is applied in the same way to all the samples from the dataset, I would expect different results if it is removed. If your results after removing it are worse, you might want to explore applying some data augmentation on the motion orientation and translation.
