### ISSUE TITLE
Regarding GT Jerk Computations

### ISSUE THREAD

**Issue by jyunlee** [BarqueroGerman/FlowMDM#5]
Hello. Thanks for the great work! 🙂
Could you explain why GT jerk values are constant numbers, which do not vary along the temporal axis (unlike the generated jerk values)?

**Comment by BarqueroGerman** [comment]
Hi!

Thank you for your interest in our work!

The GT jerk value is the average GT jerk in the dataset, i.e., the value that we should asymptotically replicate after averaging the jerk for all our generated motions. For that reason, we only consider 1 value independent of the timestep. In fact, if you randomly sample N 60-frame motion sequences from a dataset, if N is big enough you will see that the average jerk value at all timesteps (60) is almost constant. That is because the jerk value distributions are homogeneous along the time dimension in all GT motion sequences.

For the generated motions, we consider the time dimension because we look for **consistent anomalies** in the distribution of jerk values around the transitions. These anomalies are noticeable after aligning all generated motions around the transition timestep (Fig. 4 main paper). If instead we averaged along the time dimension, and then compared to GT jerk, deviated jerks below and above the GT line would cancel out, and the smoothness artifacts of MultiDiffusion might not be discernible.

Hope this is clearer now :)

**Comment by jyunlee** [comment]
Hello, German. Thanks so much for the clear explanation! 😃 Can I quickly ask one additional question regarding which set (train vs. test) you used to compute the GT jerk values?

Again, thank you for reading my question!

**Comment by BarqueroGerman** [comment]
Hi again!

Sure! We used the test set to compute the GT jerk values.

Let me know if I can help with anything else!
