### ISSUE TITLE
Why split query, key, value into rotary and non-rotary parts?

### ISSUE THREAD

**Issue by 2019211753** [BarqueroGerman/FlowMDM#6]
I am intrigued by the code on line 943 of the file 'FlowMDM/model/x_transformers/x_transformers.py':
```python
 (ql, qr), (kl, kr), (vl, vr) = map(lambda t: (t[..., :l], t[..., l:]), (q, k, v)) # split query, key, value into rotary and non-rotary parts
```
Could you please explain the rationale behind splitting the query, key, and value into rotary and non-rotary parts? I would appreciate your insight. Thank you!

**Comment by 2019211753** [comment]
Additionally, I'm curious about why the rotary embeddings are concatenated on the line 490 of the same file above:
```python
freqs = torch.cat((freqs, freqs), dim = -1)
```
 I apologize for any naivety in my questions; your explanations are greatly valued. Thank you!

**Comment by BarqueroGerman** [comment]
Hi! Thank you for your interest in FlowMDM!

Both questions are related to the RoPE implementation borrowed from the [LucidRains repository](https://github.com/lucidrains/x-transformers/blob/main/x_transformers/x_transformers.py). You can find more details on the implementation in the authors' paper [here](https://arxiv.org/pdf/2104.09864.pdf). Some insights:
1) The splitting is performed because RoPE is only applied to the first L features of the queries and keys --> _ql_ and _kl_ in L946 and L947. Splitting the values into _vl_ and _vr_ is unnecessary but it is there because it was inherited from the original code.
2) This is part of the original implementation. The freqs are needed for applying the rotary embeddings. 

Hope I could help.

German

**Comment by 2019211753** [comment]
> Hi! Thank you for your interest in FlowMDM!
> 
> Both questions are related to the RoPE implementation borrowed from the [LucidRains repository](https://github.com/lucidrains/x-transformers/blob/main/x_transformers/x_transformers.py). You can find more details on the implementation in the authors' paper [here](https://arxiv.org/pdf/2104.09864.pdf). Some insights:
> 
> 1. The splitting is performed because RoPE is only applied to the first L features of the queries and keys --> _ql_ and _kl_ in L946 and L947. Splitting the values into _vl_ and _vr_ is unnecessary but it is there because it was inherited from the original code.
> 2. This is part of the original implementation. The freqs are needed for applying the rotary embeddings.
> 
> Hope I could help.
> 
> German

Get it, thanks for your reply.
